server:
  port: 8080

spring:
  application:
    name: nexuscontact-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/nexuscontact
    username: postgres
    password: Theaprince001
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000  # 24 hours

logging:
  level:
    com.nexuscontact: DEBUG